### PR TITLE
 When passing map to for loop find first list inside and iterate using it

### PR DESCRIPTION
**Pull request by esse**

### CODE REVIEW

**Comment by jgwmaxwell** [comment]
Is this change consistent with Shopify-liquid?

**Comment by esse** [comment]
I'm not sure - however, this the only way by now which allows us to do:
```
{% if events.nodes != empty %}
        ...
        {% for event in events %}
```
in templates.

**Comment by jgwmaxwell** [comment]
Our current approach in ruby uses method-missing to synthesise this behaviour. I think a better solution here might be to use a matcher to provide the default match target as being the `nodes` wrapper.

**Comment by esse** [comment]
I tried that approach - unfortunately, that won't do the trick.

Since we're accessing:
```
{% assign events = card.events %}
{% assign total_pages = events.page_info.total_pages %}
```

first-line call matcher `def match(m, ["events"])` - same that will be called while iterating using
```
{% for event in events %}
```

therefore we impose two mutually exclusive constraints on events - one time it needs to a struct with page_info field, and at the second time it should be a list.

**Comment by jgwmaxwell** [comment]
That's irritating of us.

**Review by jgwmaxwell — APPROVED** [review]

**Comment by jgwmaxwell** [comment]
Only slight improvement thinking about it might be to add the binary-to-list to that `convert-to-list` function overload?

**Pull request merged**
